feat(mgeconvert/onnx): add support for mge to onnx with resnet18 and …
MegEngine/mgeconvert pull request #29
Opened 2021-08-12 08:42 UTC by CeryZhai

support resnet18 and resblock dump , and support op_version=10

2021-08-17 04:22 UTC, xpmemeda commented
这些mge后缀的模型文件可以用 ``TemporaryFile`` 写成代码的形式吗？时间一长可以就不记得这些模型是什么了。

2021-09-03 02:30 UTC, lixiangyin666 commented
文档加上对新加OP支持的说明

2021-09-03 02:36 UTC, lixiangyin666 requested changes

2021-09-03 02:36 UTC, lixiangyin666 commented on mgeconvert/onnx_converter/onnx_op.py
> +        print("var0 : {} , var1 : {}  var2: {}, kh: {} , kw :{} , sh :{} sw : {}".format(input_relu_var.shape,input_pooling_var.shape,input_reshape_var.shape, opr.kh,opr.kw,opr.sh,opr.sw))
去掉调试信息

2021-09-03 02:36 UTC, lixiangyin666 commented on mgeconvert/onnx_converter/onnx_op.py
> +                    "current convert can not support windows size not equal with stride size"
BaseException在这里用不合适吧，BaseException 是为系统退出异常而保留的，建议用ValueError？

2021-09-03 02:36 UTC, lixiangyin666 commented on mgeconvert/onnx_converter/onnx_op.py
> +    max_pooling  dP_prev[h*stride_h: h*stride_h + f_h, w*stride_w: w*stride_w+f_w, c] = dP[h,w,c] * (P_prev[h*stride_h: h*stride_h + f_h, w*stride_w: w*stride_w+f_w, c] == max(P_prev[h*stride_h: h*st
这里引用了pytorch的什么？

2021-09-07 10:05 UTC, closed without merging